/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Baloch
 */
import java.util.ArrayList;
import javax.swing.*;
import java.sql.*;
public class Income extends javax.swing.JFrame {

    /**
     * Creates new form Income
     */
    public Income() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jInternalFrame2.getContentPane().add(jPanel1);
        jPanel1.setBounds(983, 0, 377, 0);

        jPanel2.setLayout(null);
        jInternalFrame2.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 43, 0, 0);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome to Income Pannel"); // NOI18N
        jInternalFrame2.getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 10, 460, 63);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bills");
        jInternalFrame2.getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 80, 130, 63);
        jInternalFrame2.getContentPane().add(jTextField2);
        jTextField2.setBounds(600, 90, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teachers Pay");
        jInternalFrame2.getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 170, 250, 63);
        jInternalFrame2.getContentPane().add(jTextField3);
        jTextField3.setBounds(610, 170, 110, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gernaterrepairment");
        jInternalFrame2.getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 240, 340, 63);
        jInternalFrame2.getContentPane().add(jTextField4);
        jTextField4.setBounds(610, 250, 110, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LowerStafsalary");
        jInternalFrame2.getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 400, 340, 63);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Tell Remainig Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton1);
        jButton1.setBounds(240, 470, 400, 60);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Furniturerepairment");
        jInternalFrame2.getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 310, 340, 63);
        jInternalFrame2.getContentPane().add(jTextField5);
        jTextField5.setBounds(610, 320, 110, 40);
        jInternalFrame2.getContentPane().add(jTextField6);
        jTextField6.setBounds(610, 400, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jInternalFrame2.getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, -30, 930, 680);

        jButton2.setText("jButton2");
        jInternalFrame2.getContentPane().add(jButton2);
        jButton2.setBounds(550, 480, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Databasecon obj=new Databasecon();
        Databasecon obj1=new Databasecon();
        int k=0;
        int arry[]=new int[100];
       int h=0;        
obj.connect();
ResultSet rt=null;
      Statement st,st1=null;
      Connection con;
      obj.connect();
      obj1.connect();
      int id;
      int first,   result = 0,sum = 0,total = 0;
      String s1,s2,s3,s4,s5,s6,s7;
             int Remaingrupees;
             int Bills,LowerStafsalary;
                    int TeachersPay,Gernaterrepairment,Furniturerepairment;
            s1=jTextField3.getText();
            TeachersPay=Integer.parseInt(s1);
            s2=jTextField3.getText();
            Gernaterrepairment=Integer.parseInt(s2);
            s3=jTextField5.getText();
            Furniturerepairment=Integer.parseInt(s3);
            s4=jTextField2.getText();
            Bills=Integer.parseInt(s4);
            s5=jTextField6.getText();
            LowerStafsalary=Integer.parseInt(s5);
     
     try{
                
            String query2  = "Insert into Income2 values('"+Bills+"','"+TeachersPay+"','"+Gernaterrepairment+"','"+Furniturerepairment+"','"+LowerStafsalary+"')";              
            st= obj.con.createStatement();
            //st1= obj1.con.createStatement();
            int i =st.executeUpdate(query2);
             //int j =st1.executeUpdate(query3);
                     }catch(Exception ex){
 ex.getStackTrace();}
String query="Select * From Income";     

             
try{
           
    st=obj.con.createStatement();

             
    rt=st.executeQuery(query);

             
             while(rt.next()){// first I was confuse how to print data from database but with  alote struggle i did it 
 
             
                 arry[k]=Integer.parseInt(rt.getString("AmountPaid"));
                                          
                  
               
               sum=total;      
                 result= arry[k]+arry[k+1];
                 
                 total=sum+result;                  
                          
                  k++;  
               
                            
            
               
                }  
                 
            int incometotal=Bills+LowerStafsalary+TeachersPay+Gernaterrepairment+Furniturerepairment;
              String S10 = Integer.toString(incometotal);
            
            Remaingrupees = total-incometotal; 
            String s11 = Integer.toString(Remaingrupees);
                                
             JOptionPain.showMessageDialog(null,s11); 
               
            }catch(Exception ex){
                ex.getStackTrace();
            }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Income().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
